import { existsSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import ts from 'typescript'

/** Marks the consumer's barrel as owned by the CLI, so add may rewrite it. */
export const barrelHeader =
  '// Generated by tc96-parttens add from the installed patterns; rewritten on every add.'

// The workspace aggregate (packages/parttens/src/index.ts) is the source: the
// consumer's barrel keeps its directives and each export whose module is
// installed, so aliases such as Kanban follow their pattern.
export function aggregateBarrel(
  source: string,
  installed: (specifier: string) => boolean,
) {
  const ast = ts.createSourceFile('index.ts', source, ts.ScriptTarget.Latest)
  const kept = ast.statements.filter((statement) => {
    if (
      ts.isExpressionStatement(statement) &&
      ts.isStringLiteral(statement.expression)
    )
      return true
    if (
      !ts.isExportDeclaration(statement) ||
      !statement.moduleSpecifier ||
      !ts.isStringLiteral(statement.moduleSpecifier)
    )
      throw new Error(
        `The aggregate may only hold directives and re-exports: ${statement.getText(ast)}`,
      )
    return installed(statement.moduleSpecifier.text)
  })
  return [barrelHeader, '', ...kept.map((node) => node.getText(ast)), ''].join(
    '\n',
  )
}

/** Writes the barrel unless the consumer owns a file at that path. */
export async function writeBarrel(path: string, content: string) {
  if (existsSync(path)) {
    const current = await readFile(path, 'utf8')
    if (!current.startsWith(barrelHeader)) return 'preserved'
    if (current === content) return 'unchanged'
  }
  await writeFile(path, content)
  return 'written'
}
